apiVersion: v1
kind: Pod
metadata:
  name: didox-cpf
  labels:
    app: didox-cpf
spec:
  containers:
    - name: container-pod-cpf
      image: didox/validador-cpf-java-turma-devops
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-cpf
spec:
  type: ClusterIP
  selector:
    app: didox-cpf
  ports:
    - port: 8080
      targetPort: 8080