apiVersion: v1
kind: Pod
metadata:
  name: didox-nginx-volume
  labels:
    app: didox-nginx-volume
spec:
  containers:
    - name: container-pod-nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
